### ISSUE TITLE
What does folder/package means? 

### ISSUE THREAD

**Issue by hovancik** [AnySoftKeyboard/LanguagePack#101]
Hi,  trying to go through README but can't get over point 3 

```
In Android Studio, Refactor->Rename the folder/package com.anysoftkeyboard.languagepack.languagepack in the project tree, replacing the last languagepack with the name of the language. This will automatically change it at a couple of other locations.
```

I'm in Android Studio 2.3.3

**Comment by friesenkiwi** [comment]
What is the problem or error when following the steps of point 3?

**Comment by hovancik** [comment]
I don't know what `folder/package` mean. I don't see anything like that in project tree.

**Comment by friesenkiwi** [comment]
In Java, the package `com.anysoftkeyboard.languagepack.languagepack` has to be represented by the folder hierarchy `com/anysoftkeyboard/languagepack/languagepack/` so renaming the folder via Android Studio's "Refactor" facility in the project tree to `com/anysoftkeyboard/languagepack/YOURLANGUAGE/`, (actually renaming only the last subfolder) will automatically also rename the Java package name (which is in the first line of every .java file)

**Comment by hovancik** [comment]
Thanks!
