### ISSUE TITLE
Marked as vulnerable in F-Droid

### ISSUE THREAD

**Issue by pchampin** [AnySoftKeyboard/LanguagePack#108]
I just updated F-Droid to version 1.0 and it altered me that a number of my installed packages, including the French language package for ASK, were vulnerable.

More precisely, it has the KnownVul and DisabledAlgorithm tags, both described [here](https://f-droid.org/wiki/page/AntiFeature:KnownVuln). From what I understand, it is mostly a matter or re-packaging rather than re-coding anything...

**Comment by friesenkiwi** [comment]
This should have been solved by releasing the new french pack: https://f-droid.org/de/packages/com.anysoftkeyboard.languagepack.french/
