### ISSUE TITLE
Indonesian language

### ISSUE THREAD

**Issue by rejenrah** [AnySoftKeyboard/LanguagePack#113]
Hello there, is possible to add Indonesian language on ASK?
Thank you.

**Comment by azzamsa** [comment]
[on progress](https://github.com/AnySoftKeyboard/LanguagePack/issues/118) ...

**Comment by rejenrah** [comment]
thanks a lot

**Comment by rejenrah** [comment]
please lemme know when it's up, and thank you anyway :D

**Comment by friesenkiwi** [comment]
#118 ois now merged and i release as soon as possible
