### ISSUE TITLE
Asking recomendation fo f value in word list

### ISSUE THREAD

**Issue by azzamsa** [AnySoftKeyboard/LanguagePack#118]
@friesenkiwi  find [nice Indonesian word list](https://github.com/ardwort/freq-dist-id/blob/master/data/kompas.1gram) that crawled from specific web, so that it already contain a statistic value based on appearance.

e.g 
```
yang	795050
di	709509
dan	629540
ini	332855
itu	313570
dengan 312096
```

but I want to know what is the max and min value of `f` in user word list ?, so that I can scale those big value to match min max value of ASK.

I done little research, and some of them e.g [dutch](https://github.com/OpenTaal/LanguagePack/tree/Dutch/dictionary) contain only 72 - 255.

I have [this simple awk script](https://github.com/azzamsa/ask-words-id/blob/master/script/scale_num.awk) to scale all number wich work nice. But I am asking the recommended minimum value, is it 72, 1 or other ?

``` awk
function scale_between(unscaled_num, min_allowed, max_allowed, min, max) {
    scaled_num = int((max_allowed - min_allowed) * (unscaled_num - min) / (max - min) + min_allowed);

}

{
    scale_between($2, 1, 255, 271, 795050);
    print $1, scaled_num;

}
```
PS: using this script the result will be like: 

<table>
<tr>
<td>
   <pre lang="">
pemerintah      45524
pun     45026
jika    44460
jalan   43671
dinobatkan      274
memperbanyak    271
   </pre>
</td>
<td>
  <pre lang="">
pemerintah 15
pun 15
jika 15
jalan 14
dinobatkan 1
memperbanyak 1
  </pre>
</td>
</tr>
</table>

Thank you.

**Comment by azzamsa** [comment]
@menny @friesenkiwi  after you recomendation and guide about range of `f` value, I will continue my work as soon as possible to add ASK for indoensia language.

**Comment by menny** [comment]
Yes, that's correct. The values should be between 1-255.

**Comment by azzamsa** [comment]
> Yes, that's correct. The values should be between 1-255.

okey, back to work ...
