### ISSUE TITLE
Create a branch for Afrikaans language

### ISSUE THREAD

**Issue by markwmuller** [AnySoftKeyboard/LanguagePack#121]
Please create a branch for Afrikaans so that I can create the appropriate pull request.

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/LanguagePack/tree/Afrikaans

**Comment by menny** [comment]
thanks!

**Comment by friesenkiwi** [comment]
Merged at https://github.com/AnySoftKeyboard/LanguagePack/pull/122
