### ISSUE TITLE
Any reason why the french language pack is not in the F-Droid store?

### ISSUE THREAD

**Issue by schodet** [AnySoftKeyboard/LanguagePack#127]
If none, could I help too add it?

**Comment by menny** [comment]
Please, go ahead and add it.

**Comment by schodet** [comment]
OK, thanks.

**Comment by menny** [comment]
@schodet please report back here on your progress.

**Comment by schodet** [comment]
Someone did it two days ago!

https://gitlab.com/fdroid/fdroiddata/merge_requests/3019

https://gitlab.com/fdroid/fdroiddata/issues/1164

**Comment by friesenkiwi** [comment]
Thank you for your contribution!
