### ISSUE TITLE
Need help reviewing and packaging : Tamazight Large Pack

### ISSUE THREAD

**Issue by BoFFire** [AnySoftKeyboard/LanguagePack#132]
Hi @menny 
I need reviewing and packaging, if you have time.

- Link to repo : https://github.com/BoFFire/LanguagePack
- Link to F-Droid : https://gitlab.com/BoFFire/fdroiddata/blob/master/metadata/com.anysoftkeyboard.languagepack.tamazight.txt

Thank you :)

**Comment by menny** [comment]
I see a few issues. I want to suggest that you create a PR, to merge this back into `AnySoftKeyboard/LanguagePack` and I can comment there. Sounds good?
What is the name of the pack? I see you have a few languages packed together

**Comment by BoFFire** [comment]
PR open : https://github.com/AnySoftKeyboard/LanguagePack/pull/133

**Comment by BoFFire** [comment]
Next version, Arabic dictionary will be based on the excellent work of @linuxscout Ayaspell
https://github.com/linuxscout/ayaspell/tree/master/dict

**Comment by BoFFire** [comment]
My ASK "ar" localizations are here : https://crowdin.com/project/anysoftkeyboard/activity_stream

**Comment by menny** [comment]
thanks.
I'm closing this issue. We'll continue the discussion on the PR page.
