### ISSUE TITLE
Spanish Keyboard (Catalan layout): missing grave accents

### ISSUE THREAD

**Issue by ZJaume** [AnySoftKeyboard/LanguagePack#137]
The grave accents (`) that are used with 'a', 'e' and 'o' vocals (àèò) are not displayed and they're very important in the language. Also the 'a' is only combined with grave accent (à) and never with acute mark (á).
Edit: diaeresis is also missing for 'u' and 'i' which is commonly used.
![ask-bugreport1](https://user-images.githubusercontent.com/11339330/39754636-599dc072-52b2-11e8-958a-b2cec9cdf65f.png)

**Comment by friesenkiwi** [comment]
Thanks for your report and contribution, closing this as the PR is now merged.
