### ISSUE TITLE
Centralization of language pack

### ISSUE THREAD

**Issue by homersimpsons** [AnySoftKeyboard/LanguagePack#14]
Maybe you can create each languague pack separately in this repository to easily improve them. Another Idea is to allow the user to download language pack in the app and theme for keyboard as apk and let the user choose which keyboard to associate with each language pack .

**Comment by PanderMusubi** [comment]
About three years ago, they were residing in branches in this repository. Now you have linked forks such as https://github.com/pelya/AnySoftKeyboard-LanguagePack-Russian and unlinked forks such as https://github.com/rhornig/anysoftkeyboard-hungarian and is indeed hard to control general improvements over all language packs.

I am about to start two language packs and am wondering how to approach that? Is, for now, forking this repository the way to go?

**Comment by PanderMusubi** [comment]
What sorting of words.xml and autotext.xml is preferred by AnySoftKeyboard? In other words, makes it loads the quickest?

**Comment by SvGeloven** [comment]
Could someone please review my initial version for Dutch language pack https://github.com/OpenTaal/LanguagePack-Dutch and tell me what next steps to take.

**Comment by friesenkiwi** [comment]
As this is a kind of very mixed topic, and I think that most questions have been addressed or are obsolete by now, I'm closing this issue for now.
Please reopen if i am mistaken!

For the record: Most packs are maintained here as forks and released through F-Droid and Play Store, some are not yet transferred from the old SVN repository but that is in the works (see https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/690 ), some are released independently by the community, some of those are mentioned in https://github.com/AnySoftKeyboard/LanguagePack/blob/master/README.md.
The way to go to start a new pack is to fork the repo and make a new branch, which is now also described in the README.
