### ISSUE TITLE
New branch creation request - Songhay (son) language

### ISSUE THREAD

**Issue by Afudu** [AnySoftKeyboard/LanguagePack#145]
Dear Team,

Please add a branch for Songhay (son), so i can prepare the appropriate pull request.

Thanks

**Comment by Afudu** [comment]
closed by mistake

**Comment by friesenkiwi** [comment]
Created the branch: https://github.com/AnySoftKeyboard/LanguagePack/tree/Songhay
Really looking forward to this, thank you already for your contribution! :-)
What will be the Symbol/Flag? http://althistory.wikia.com/wiki/File:Flag_of_Songhai.png ?
