### ISSUE TITLE
Please add a new branch for Sardinian (sc)

### ISSUE THREAD

**Issue by asereze** [AnySoftKeyboard/LanguagePack#161]
I managed to create a working language pack for Sardinian, by modifying the xml files for the wordlist manually (I left the files i tried to use with parseTextInputFiles as a reference, even if the character issue is still not solved and mergeAllWordList uses other ones). Please add a Sardinian branch so that I can create a pull request.

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/LanguagePack/tree/Sardinian
Here you go. Thank you!

**Comment by asereze** [comment]
Thanks a lot!
