### ISSUE TITLE
Lithuanian language pack no longer on Google Play

### ISSUE THREAD

**Issue by rimas-kudelis** [AnySoftKeyboard/LanguagePack#168]
Hi,
the previously available Lithuanian language pack is now gone from the Play Store. Is there any chance to see it there again?

**Comment by Baltix** [comment]
Lithuanian package is gone from F-droid repo too 😂 How we can help to have Lithuanian language keyboard pack in Fdroid and Google Play repos?

**Comment by rimas-kudelis** [comment]
The pack is now resurrected, and we're working on transitioning its ownership.

**Comment by Tichij** [comment]
Very good news :thumbsup:
