### ISSUE TITLE
Basque language pack not available on Google Play

### ISSUE THREAD

**Issue by aldatsa** [AnySoftKeyboard/LanguagePack#175]
A user that wanted to install the Basque language pack noticed that it isn't available on Google Play: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.basque

**Comment by menny** [comment]
Sorry for the late reply. I've fixed the issue. It should be available again.

**Comment by aldatsa** [comment]
Thank you very much @menny!
