### ISSUE TITLE
Error con las tildes

### ISSUE THREAD

**Issue by Benitoes** [AnySoftKeyboard/LanguagePack#195]
En el teclado español, han desaparecido todas las tildes de las vocales salvo la tilde aguda. No se puede poner la diéresis, por ejemplo, que es un caracter habitual en el español

**Comment by Benitoes** [comment]
Me alegra saber que ya está arreglado, además lo estoy probando y está perfecto. Pero no entiendo tu respuesta, me dices que ya estaba reportado en el #199 cuando éste es el #195, mi reporte es de hace dos meses y el otro de hace 22 días 😳

En todo caso, gracias por el aviso.

No me gusta la decisión de que al dejar pulsada una letra que puede llevar acento salte como primera opción un número si la letra es de la primera fila. Vuelve a ser incómoda la escritura, en mi opinión.

Un saludo.

**Comment by worg** [comment]
perdona tienes razón, éste issue es anterior, como ya está resuelto podríamos cerrar el issue?

**Comment by Benitoes** [comment]
Sì, claro

**Comment by menny** [comment]
Thank you for reporting. I understand that the latest version fixed this?
