### ISSUE TITLE
Relative links in README.md

### ISSUE THREAD

**Issue by Taknok** [AnySoftKeyboard/LanguagePack#218]
Hi,

Why not using relative links in the README.md ? With them, forked repositories will point images and sources to themselves and not to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/LanguagePack).
For example when adding a new language pack to the mono repo, with a link to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/LanguagePack) the flag or the sources will not works since they are not yet PR and accepted. With relative links they will load.
Example : 
- modifications : Taknok/LanguagePack@172255c.
- result : [Taknok/LanguagePack/README.md](https://github.com/Taknok/LanguagePack/blob/master/README.md#languages-in-this-repo)

Also the file is easier to read in raw : links are shorter.

**Comment by azzamsa** [comment]
@menny I think this is a good idea, what do you think ?

**Comment by menny** [comment]
Thanks, done.
