### ISSUE TITLE
Two French Canadian Keyboards, cannot configure AnySoftKeyboard to use just one

### ISSUE THREAD

**Issue by connerbw** [AnySoftKeyboard/LanguagePack#222]
I use the QWERTY French Canadian keyboard.

A few days ago an upgrade was pushed to my Android and I now have two, more or less identical QWERTY French Canadian keyboards. One with symbols, the other without. I only want one. When I try to select just one of them, my settings are ignored, both are always selected.

Steps to reproduce:

1) In settings, deselect *all* French keyboards
2) Select 1 of the 2 QWERTY French Canadian keyboards
3) Exit 
4) Go type something, cycle through available keyboards.

Expected: One QWERTY French Canadian keyboard

Actual Two QWERTY French Canadian keyboards

![image](https://user-images.githubusercontent.com/812192/51116659-bd226200-17d9-11e9-9a10-d53e9542493f.png)

**Comment by migrick** [comment]
Again since the last update the french canadian option is not avaliable. There is 2 options, french and french with accent but they are the same with no accent on e and a.
Thank you to take care of that like last time.

**Comment by connerbw** [comment]
> the french canadian option is not avaliable.

@migrick I'm not sure the context of this message. I see the French Canadian keyboards just fine. Did you [install the French Languag pack](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.french&hl=en_US)? 

My issue is that I cannot select **just one** of them. See screenshot:

![image](https://user-images.githubusercontent.com/812192/51116659-bd226200-17d9-11e9-9a10-d53e9542493f.png)

If you still can't see the keyboards, after install the French language pack, please open a new issue.

Regards,

**Comment by migrick** [comment]
I see the same thing as you, 2 french package, 1 is french and the other one, french with accent. Like you I select one and two appear but they are the same with no accent.I need the one with accent.

Envoyé à partir de Yahoo Courriel sur Android 
 
  Le lun., janv. 14 2019 à 8:53 a.m., Dac Chartrand<notifications@github.com> a écrit :   

the french canadian option is not avaliable.


@migrick I'm not sure the context of this message. I see the French Canadian keyboards just fine. Did you install the French Languag pack?

My issue is that I cannot select just one of them. See screenshot:



If you still can't see the keyboards, after install the French language pack, please open a new issue.

Regards,

**Comment by RGagne0227** [comment]
I have the same issue, i cannot select only one of the two qwerty french keyboards, both gets selected...

Also, once they are select, when i cycle through the keyboards, only the one with symbols is available and i can not get to use the one with accentuated characters...

**Comment by Taknok** [comment]
Hi,

Both keyboards are selected because the same [`nameresId`](https://github.com/AnySoftKeyboard/LanguagePack/blob/2a1328b198b5c0f5cf69c853b7c0767cad885077/languages/french/pack/src/main/res/xml/french_keyboards.xml#L21) is used. I fix it asap, update should be there in a day on playstore

**Comment by menny** [comment]
The fix was merged.
Will be available in the Play-Store in a few hours.

**Comment by menny** [comment]
Thank you for the fix!

**Comment by migrick** [comment]
Thank you for the update. Everything is back to normal.

Envoyé à partir de Yahoo Courriel sur Android 
 
  Le mar., janv. 15 2019 à 9:55 a.m., Menny Even Danan<notifications@github.com> a écrit :   
Closed #222.
