### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by HorvathPeterHub** [AnySoftKeyboard/LanguagePack#23]
As of the latest update the right button in the upper bar disappeared. This is an intended issue by the release notes, but now the only way to switch back from the symbol layout to the normal is to swipe.
![tmp_32279-screenshot_20161224-1436481813796454](https://cloud.githubusercontent.com/assets/24753465/21467309/25417ad8-c9e9-11e6-8611-51336b016a0c.png)

**Comment by menny** [comment]
track this here: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/801
