### ISSUE TITLE
New language pack: Nias

### ISSUE THREAD

**Issue by sslaia** [AnySoftKeyboard/LanguagePack#238]
Hello,
I have created the language pack for my mother tongue spoken mainly on Nias Island, Indonesia following your recent instruction. Everything is ready: the dictionary, the icons, the keyboard layout etc. (see the attached screenshot of the keyboard layout with the next word prediction active). After testing it for a while now I think it is ready to be proposed.

I would be grateful if you could accept this new language pack in ASK.

Thank you very much.

![nk-in-action](https://user-images.githubusercontent.com/44895234/52277712-3f232800-294d-11e9-9a20-46dd6431a261.jpg)

**Comment by menny** [comment]
I would love to!
Please, open a PR with the changes.

I can also publish that to Google Play Store if you wish.
