### ISSUE TITLE
Ukrainian regular layout is missing the Ґ (ґ) letter on the Г pop-up

### ISSUE THREAD

**Issue by gordonel** [AnySoftKeyboard/LanguagePack#284]
Ukrainian contains Ґ (ґ) letter, which is a derivative from Г. The letter is present on the four-row variant, but is absent on the regular one. It should be in the pop-up for the Г letter, which is on the U position of the standard QWERTY.

**Comment by yurkobb** [comment]
I suppose that #254 fixes this?

**Comment by gordonel** [comment]
Looks like it

**Comment by menny** [comment]
I've also released it to Play-Store.

**Comment by yurkobb** [comment]
Thanks! F-Droid too?
