### ISSUE TITLE
German Source

### ISSUE THREAD

**Issue by jugendhacker** [AnySoftKeyboard/LanguagePack#289]
I currently try to update the German language pack in the Fdroid, because I saw that there are several updates in the Playstore for it. The problem is that I couldn't find the source anymore so it's impossible for fdroid to release the new updates. Where could I find it?

**Comment by biphasic** [comment]
is it the one in a [separate branch](https://github.com/AnySoftKeyboard/LanguagePack/tree/German)?

**Comment by jugendhacker** [comment]
I think that could be the one... but the latest playstore release isn't tagged anywhere as I can see... but could also me beeing to unable to find it...

**Comment by menny** [comment]
the `German` branch is the latest code.

You will do a great service to the community if you bring that code into `master`.
I'm working on a way to semi-automate the process of figuring out what is the right metadata entry to add to fdroid when updating a language-pack.

**Comment by jugendhacker** [comment]
The best way would be if the playstore versions code would be tagged then it's easy to bring it automatically up to fdroid... 

Could you tell me what commit version 2.0.279 (Version Code 257) is?

**Comment by ArenaL5** [comment]
@martholomew: Didn't you merge German branch into master with your commit 34db32f451305f6d2eba847ffa8948983768d438?

**Comment by martholomew** [comment]
Yeah, @menny this can be closed.

**Comment by jugendhacker** [comment]
Oh cool then I'll close it and try to get the build working on fdroid....
