### ISSUE TITLE
Options for 2-Bulsik

### ISSUE THREAD

**Issue by Cosmic-Onion** [AnySoftKeyboard/LanguagePack#302]
Hello, I've put together a korean keyboard but the characters don't work properly as they only output one at a time and do not stack as they would if using 2 or 3 bulsik.

Am I missing something?

**Comment by Cosmic-Onion** [comment]
also I'm using llineageOS if that is any help. I've uploaded the repo now

**Comment by pierreN** [comment]
Upvote for this. That the only thing left for me.to.switch from Swiftkey to AnySoftKeyboard. 

I can help with coding. I guess we need to modify the main app as well. Any clue where to start please ?

Thanks
