### ISSUE TITLE
[UI Bug] [Brazilian Portuguese] Keyboard name is 'Root', should be 'Brazilian Portuguese'

### ISSUE THREAD

**Issue by papb** [AnySoftKeyboard/LanguagePack#304]
When viewing Virtual Keyboard settings:

![this](https://user-images.githubusercontent.com/20914054/69016215-47e46800-097b-11ea-9624-c20c6d6e8123.jpeg)

It shows this mysterious `Root` name but I would expect `Brazilian Portuguese`

**Comment by menny** [comment]
This repository is being archived.
Please move this issue to http://github.com/AnySoftKeyboard/AnySoftKeyboard/issues
