### ISSUE TITLE
Info for New Layout

### ISSUE THREAD

**Issue by si6ned** [AnySoftKeyboard/LanguagePack#319]
Hi all, 

i would like to do my own Version of the german layout. For that i'm following Kertase's Commit
[https://github.com/AnySoftKeyboard/LanguagePack/pull/314/files](url)

Since I only want to add an xml and make minor changes I don't need Gradle or Android Studio, right? I'm struggeling with the new id in [languages/german/pack/src/main/res/xml/german_keyboards.xml ](url) though, how do I get it?

`    <Keyboard nameResId="@string/de_keyboard_neo2" iconResId="@drawable/ic_status_german"
              layoutResId="@xml/de_neo2" id="ad1b5ffa-15cc-4ba4-abb7-68df2c0874e7"`

Any help appreciated!

**Comment by martholomew** [comment]
Generate a random new id [here](https://www.guidgenerator.com/). Hope that helps.

**Comment by si6ned** [comment]
All right, thanks!

**Comment by si6ned** [comment]
For anyone interested, I made my own repo for the german language pack

with layouts with more popup characters and functional keys:
[https://github.com/si6ned/LanguagePack](url)

These 3 keyboards were added:
[https://github.com/si6ned/LanguagePack/blob/master/languages/german/pack/src/main/res/xml/de_qwertz_equal.xml](url)
[https://github.com/si6ned/LanguagePack/blob/master/languages/german/pack/src/main/res/xml/de_qwertz_broad.xml](url)
[https://github.com/si6ned/LanguagePack/blob/master/languages/german/pack/src/main/res/xml/de_qwertz_extra.xml](url)
