### ISSUE TITLE
Bad ergonomy on Brazilian Portuguese keyboard

### ISSUE THREAD

**Issue by biguibi** [AnySoftKeyboard/LanguagePack#336]
In Brazilian Portuguese, we use accentuated characters a lot. An example is the word.. "is" which is "É", however currently it is uncomfortable to type said accentuated keys since the most used ones are mostly farther from the key you start holding, more specifically, your finger has to travel more to type a really common character on the language, take for example the distance of the "É" key on AnySoftKeyboard and AOSP Keyboard on a Tablet.

![Screenshot_20191224-152137](https://user-images.githubusercontent.com/58740650/71422733-17bb7380-2663-11ea-8683-5a182352c01a.png)
![Screenshot_20191224-153052](https://user-images.githubusercontent.com/58740650/71422740-1f7b1800-2663-11ea-9def-90f05b0288d1.png)

This could possibly be solved if the popup expanded to both sides instead of only one side like it does on the AOSP Keyboard.
The letter E is not the only one affected by this issue, all vowels are.

**Comment by martholomew** [comment]
This is interesting and seems more like an issue for the app's repository if you would like to move the issue over [there](https://github.com/AnySoftKeyboard/AnySoftKeyboard).
