### ISSUE TITLE
English language pack popup characters are not sane

### ISSUE THREAD

**Issue by hoshsadiq** [AnySoftKeyboard/LanguagePack#337]
Hello, I wanted to make some suggestions, and possibly even raise a PR. In the past I have tried to use AnySoftKeyboard but ended up going back to the stock keyboard for a few simple reasons. Though, my biggest hurdle is that the current popup characters are not sane for the English character map.

Most of the characters that come up when opening the popup characters. Specifically characters like `ľĺłλ`, `ŵω`, `àáâãāäåæąăα`. These are not necessary, and take away from the experience. These popup keys should be either replaced by more useful keys or removed.

The normal `qwerty_with_symbols` keyboard is a massive improvement on the `qwerty` but it's still not there yet.

If these characters are needed for anything that's not English, and additional language that reflects that specific language should be created.

I suggest we take inspiration from other keyboards and get rid of many of these characters. I think a popular app like SwiftKey/Gboard should be taken as inspiration.

I'd be happy to try and raise a PR based on what I think should be in a keyboard popup characters (and in my opinion, it should eventually become to default), however, I have questions.

- I'm currently not in a position to be able to build Android apps, so I will not be able to test.
- Would it be preferred to replace one of the qwerty keyboards, or would a new keyboard be preferred.
- Regardless of which is the preference, is editing the corresponding `.xml` enough? Or is there more things to edit?

**Comment by MegaArthur** [comment]
For me one of the most appealing features of ASK is the myriad special characters. If you want to make a stripped-down version, create an alternative Eng layout.

**Comment by martholomew** [comment]
I agree, and we have a [pull request](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1921) on the app's repository to fix this problem and hopefully make everyone happy.
