### ISSUE TITLE
IPA (International Phonetic Alphabet) 

### ISSUE THREAD

**Issue by antoniomaraspin** [AnySoftKeyboard/LanguagePack#340]
Is it possible to make a package or an in-app option, maybe? Thx

**Comment by menny** [comment]
@martholomew , what do you think?

**Comment by antoniomaraspin** [comment]
What do I think? That you have to tell me about that!

**Comment by martholomew** [comment]
Interesting idea, I'll look into it and see how much work that'd be

**Comment by menny** [comment]
This repository is being archived.
Please move this issue to http://github.com/AnySoftKeyboard/AnySoftKeyboard/issues
