### ISSUE TITLE
migrate this repository into AnySoftKeyboard main repo

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/LanguagePack#345]
There is no need for this repo to be standalone, it can be integrated with the main app repo.

**Comment by menny** [comment]
I'll start researching how to move this repo's code, required toolings, CI scripts and its history to the main repo.

@martholomew we'll need to finish development on this repo. Which means all open issues and PRs need to be resolved. Can you go over the PRs and see what can be closed and what can be merged?

Thank you

**Comment by martholomew** [comment]
Sure, I'll start on that.

**Comment by martholomew** [comment]
Alright, took care of the pull requests. I'll start on the issues later maybe.

**Comment by oxr463** [comment]
> 
> 
> There is no need for this repo to be standalone, it can be integrated with the main app repo.

What is the reasoning behind this change? Just curious.

**Comment by menny** [comment]
A few :
* share tools between projects
* share build system
* one set of code quality tools
* share source-level dependencies between projects and not worry about bumping maven dependencies
* easier discoverability

**Comment by menny** [comment]
done
