### ISSUE TITLE
German:  Add "German+" Layout

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AnySoftKeyboard/LanguagePack#349]
Similar to how there is a "German Broad" and a "German Broad +" layout, there should be a keyboard with extra pop-ups that uses the standard "German" Layout. (the one with ä,ö, and ü on the right side)

Ideally, it would be the same pop-ups that "German Broad +" - layout uses... while still keeping the special letters on the right the same.

Edit: This might be the same thought the feature-request #285 was going for.

**Comment by menny** [comment]
This repository is being archived.
Please move this issue to http://github.com/AnySoftKeyboard/AnySoftKeyboard/issues
