### ISSUE TITLE
German:  Option to remove the "ß"-Key from the bottom right.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AnySoftKeyboard/LanguagePack#350]
### Improvement
To make users that switch from (for example) the Samsung Keyboard to ASK, i suggest adding the option to remove the ß-key from the bottom right. 

This extra space could be used either to increase the size of the remaining letter-keys, or, and this is big, use it to make the backspace-key bigger.
This would be great because the backspace-key feels really small when first switching to AnySoftKeyboard. With every layout.

### Implementation
There should either be a switch somewhere, or there should be extra layouts that have the ß-key removed.

For this change to be implemented, there first needs to be an alternative way to type " ß ". Which is one reason, why #349 should be implemented first / is more important.

**Comment by menny** [comment]
This repository is being archived.
Please move this issue to http://github.com/AnySoftKeyboard/AnySoftKeyboard/issues
