### ISSUE TITLE
German reduced language pack

### ISSUE THREAD

**Issue by JuNo13** [AnySoftKeyboard/LanguagePack#4]
I'm using the german language pack on my S4,
no problem the keys are large enough. But using this setup on the S4
mini the keys get a bit small. Therefore the question:
Is there a german qwertz-layout available with less (no ä,ö,ü,ß
etc) but larger keys?
Actually I'm using the english layout but this is qwerty :-(

**Comment by friesenkiwi** [comment]
@menny this can be closed now :-)

**Comment by menny** [comment]
👍
