### ISSUE TITLE
Typo in Russian 2.0  tag

### ISSUE THREAD

**Issue by krt16s** [AnySoftKeyboard/LanguagePack#49]
Russian 2.0 is tagged as `russion_2.0` instead of `russian_2.0`. Could you add (not replace) the correct tag?

**Comment by menny** [comment]
😂 oh my goodness
Yes, will do that later today

**Comment by menny** [comment]
Done: https://github.com/AnySoftKeyboard/LanguagePack/tree/russian_2.0
and also the new version: https://github.com/AnySoftKeyboard/LanguagePack/tree/russian_2.0.1

Thanks for noticing.
