### ISSUE TITLE
Icelandic Language Pack

### ISSUE THREAD

**Issue by aevare** [AnySoftKeyboard/LanguagePack#61]
Icelandic languagepack and dictionary. The dictionary is from Firefox, released under GPL v2.
The frequencies are not correct, I will try to update that at a later date.

https://github.com/aevare/LanguagePack/tree/Icelandic/

### title
Íslenskur tungumála pakki

### promo
Íslenskur tungumála pakki fyrir AnySoftKeyboard

### description
AnySoftKeyboard lyklaborðs pakki: Íslenskt lyklaborð og orðabók.

Þetta er viðbót fyrir AnySoftKeyboard. Settu upp AnySoftKeyboard fyrst, veldu svo þennan pakka i AnySoftKeyboard's Settings->Keyboards menu.

**Comment by friesenkiwi** [comment]
Hi @aevare , thank you for your work!
I created a new Icelandig branch here: https://github.com/AnySoftKeyboard/LanguagePack/tree/Icelandic
Please open a PR against this.

**Comment by friesenkiwi** [comment]
Closing this in favor of https://github.com/AnySoftKeyboard/LanguagePack/pull/74
