### ISSUE TITLE
Several combination for one key

### ISSUE THREAD

**Issue by Goodevil95** [AnySoftKeyboard/LanguagePack#62]
I trying to associate letter "х" to alt+o and i got it. But when i trying to press shift+alt+0 do not get "X". I tryed to add this line:
`<SequenceMapping keySequence="44" altModifier="true" shiftModifier="true" targetChar="X" />`
and I always get "X", with pressing shift and without shift.
This is a bag? Or i doing something wrong?

**Comment by friesenkiwi** [comment]
@menny can you help here?

**Comment by menny** [comment]
This should be a bug with main ASK. can you open it there?

**Comment by Gena95** [comment]
@menny Do you mean move issue or open new?

**Comment by friesenkiwi** [comment]
@Goodevil95 please open a new issue (with the same or more content) at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues and close this one. Unfortunately, it is not possible on GitHub, to move issues between repositories.

**Comment by Goodevil95** [comment]
@friesenkiwi thanks!
