### ISSUE TITLE
Moroccan Tamazight Tifinagh languagePack

### ISSUE THREAD

**Issue by DanShai** [AnySoftKeyboard/LanguagePack#64]
implemented and tested om my phone and ready to upload !

**Comment by menny** [comment]
Would you like ymto create a PR and share the code of this language pack?

**Comment by DanShai** [comment]
yes sure !

**Comment by DanShai** [comment]
added!  the png icons I may do them later.. at the moment they are using defaults icons.

**Comment by DanShai** [comment]
here is my branch in the forked languagepack : https://github.com/DanShai/LanguagePack/tree/Tifinagh

**Comment by DanShai** [comment]
Hi Menny, When Will you merge it?

**Comment by friesenkiwi** [comment]
Closing this in favor of https://github.com/AnySoftKeyboard/LanguagePack/pull/66
