### ISSUE TITLE
Adding Indonesian Language Pack

### ISSUE THREAD

**Issue by azzamsa** [AnySoftKeyboard/LanguagePack#67]
this is an Indonesian languagepack and dictionary.

[https://github.com/azzamsa/ask-indonesian-keyboard](url)

Translation : 
---
###  title
Paket Bahasa Indonesia

###  promo
Paket Bahasa Indonesia untuk AnySoftKeyboard

### description
AnySoftKeyboard Paket Bahasa Indonesia : kamus dan papan ketik Indonesia

Ini adalah paket ekspansi untuk AnySoftKeyboard. pasang AnySoftKeyboard terlebih dahulu, kemudian pilih tata letak yang diinginkan dari menu AnySoftKeyboard Settings-> Keyboards.

**Comment by menny** [comment]
@friesenkiwi can you take a look at https://github.com/azzamsa/ask-indonesian-keyboard ?

**Comment by friesenkiwi** [comment]
Closing this in favor of #72
