### ISSUE TITLE
German: Großes scharfes s

### ISSUE THREAD

**Issue by mueller-ma** [AnySoftKeyboard/LanguagePack#69]
Today there is a capital ß. It should be displayed instead of SS
https://unicode-table.com/de/1E9E/
http://www.n-tv.de/ticker/Scharfes-S-kommt-auch-als-Grossbuchstabe-article19912013.html

**Comment by friesenkiwi** [comment]
Hi and thanks for the suggestion. Yes, I think, you are right, ẞ (capital) should be used. I am not yet completely sure how, but will try to do it for the three layouts in the German pack. But what do you mean by SS? In the current Version, the letter ß (small) is just used for small and capital mode or is it different for you?

**Comment by mueller-ma** [comment]
You can see a "SS" when you are in capital mode, however it will print ß

**Comment by friesenkiwi** [comment]
On my device (CM13, Android 6.0.1), the German keyboard shows ß both for lower and upper case, it seems for other devices it may also show ß for lower and SS for upper case. Both ways were correct before the change.
To use https://en.wikipedia.org/wiki/Capital_%E1%BA%9E as the capital letter, we need a way to explicitly declare a capital letter to use in the XML:
`<key android:codes="223" android:keyLabel="ß" android:popupCharacters=""/> `
This is still under investigation.

**Comment by friesenkiwi** [comment]
It seems, that 
`<key android:codes="223" android:keyLabel="ß" android:popupCharacters="" ask:shiftedCodes="0x0914" ask:shiftedKeyLabel="\u0914" />`
Should be the way to go, I will check this out soon.

**Comment by friesenkiwi** [comment]
Closed via #76
