### ISSUE TITLE
Help with creating a new Macedonian pack

### ISSUE THREAD

**Issue by ikocevski** [AnySoftKeyboard/LanguagePack#71]
I'd really like to make a language pack but I don't know **anything** about Android code.
Do you think I'll manage to make it on my own and are there any tutorials that are straight forward for this type of thing? Any resources I could use to make it easier for me?

**Comment by ikocevski** [comment]
Actually, never mind I found my language on the Play Store, it wasn't on F-Droid, sorry.

**Comment by friesenkiwi** [comment]
Hey @ikocevski which language was it? If it is only available on Play Store, maybe it would be worth making your own as open source and we can publish it through F-Droid?

**Comment by ikocevski** [comment]
It's Macedonian. I'd gladly make my own if I knew how to and if it doesn't take like ages to do it.

**Comment by friesenkiwi** [comment]
@ikocevski no, it doesn't take ages and it is quite easy to learn, there are not even real programming skills necessary.
Did you already check https://github.com/AnySoftKeyboard/LanguagePack/blob/master/README.md on how to do it?
The Play Store app (https://play.google.com/store/apps/details?id=com.anysoftkeyboard.macedonianpack.stole_lazarevski) seems to be quite old, and I think @Drakuwa is the original author, maybe he cares to open source it?
Even if not, there is an old Bulgarian language pack (https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.bulgarian), whose sources are available online (https://code.google.com/archive/p/softkeyboard/source/default/source) and due to be uplifted to this repo. As I just learned, the two languages seem to be a little bit related, maybe that pack might be a good start for you?
Usually the biggest problem is the dictionary, maybe have a look at https://github.com/AnySoftKeyboard/LanguagePack/pull/78 to get an idea...?

**Comment by ikocevski** [comment]
Okay, I'll try.. I'll follow the readme and start from scratch actually.

**Comment by ikocevski** [comment]
Can I delete Android Studio after doing steps 3 and 4? Takes up too much space.

**Comment by menny** [comment]
Safest, if you delete it _after_ we merge your PR

**Comment by friesenkiwi** [comment]
Since you started so quickly, I already created the branch Macedonian for you to put up  your PR against later ;-)

**Comment by ikocevski** [comment]
@friesenkiwi Yeah, thanks I noticed that. I'm almost finished I guess.

**Comment by ikocevski** [comment]
@friesenkiwi @menny For the dictionary, can I just use a wordlist or do I have to have actual texts with real sentences?

**Comment by friesenkiwi** [comment]
Wordlist will work, but actual texts will help to derive frequencies.

**Comment by ikocevski** [comment]
@friesenkiwi Alright, so the word suggestions are placed by frequency, are they also placed in relation to the next/previous word in these texts?

Can I include both a wordlist and a conversation type text? Will that be okay?

**Comment by ikocevski** [comment]
@menny @friesenkiwi Can you please explain a bit how to set up the dictionary? I know I can include both a wordlist and texts and the app somehow makes the xmls automagically, also found the autotext.xml which is used for the commonly mistaken words.

I have two .txt files which I want in the dictionary and I want to add more later, can you please explain what should I do to properly build the xmls out of them thus enabling a basic dictionary?

**Comment by friesenkiwi** [comment]
@ikocevski please read https://github.com/AnySoftKeyboard/LanguagePack/pull/78#issuecomment-314683119 for some explanations on the dictionary. (We should add this info to the README... ;-) )
To use multiple .txt input files, you can add those as new lines to the `inputFiles` array in the `parseTextInputFiles` task in `build.gradle`. 
I think yes, the words should be case sensitive.
I don't know whether the generated dictionaries include relations of words among each other / frequency in relation to the next/previous word in texts, but I doubt it. I think, that is something ASK "learns" during usage while you type.

@menny can you confirm this?

**Comment by ikocevski** [comment]
@friesenkiwi Alright.. I finally figured out what is wrong. The lists that are generated in xml only output **Latin** words but I need **Cyrillic**. The .txt files are saved as UTF-8 but no Cyrillic words show up.
Any ideas?

**Comment by menny** [comment]
At a look at the Hebrew pack, it adds the Hebrew characters: https://github.com/AnySoftKeyboard/LanguagePack/blob/Hebrew/build.gradle#L93

**Comment by ikocevski** [comment]
L64: `def cyrillicCharacters = "љњертѕуиопшѓасдфгхјклчќжзџцвбнм".toCharArray()`
L65: `def additionalCyrillicCharacters = "ѐѝ".toCharArray()`

![studio64_2017-07-22_15-39-37](https://user-images.githubusercontent.com/29078617/28491551-175e1e84-6ef4-11e7-9f77-943cb2401c37.png)

0 Entries in the xml files.

**Comment by friesenkiwi** [comment]
I just checked https://github.com/ikocevski/LanguagePack/blob/Macedonian/build.gradle but it seems that's not the latest version?
You could already put up a PR to https://github.com/AnySoftKeyboard/LanguagePack/tree/Macedonian, just mark it "[WIP] " in the title. That might make things easier to spot differences, merge conflicts and communicate via line comments... ;-)

**Comment by ikocevski** [comment]
Okay, I'll do that right now.

**Comment by friesenkiwi** [comment]
Closing this in favor of #80 .
