### ISSUE TITLE
Improper Handling of Shift Key for Indian Languages

### ISSUE THREAD

**Issue by ani221989** [AnySoftKeyboard/LanguagePack#8]
We are developing Language Pack for 22 Indian Languages. However, we are facing some issues regarding developing Language Pack.
1) Indian Language characters and conjuncts on both Shift and Unshift layers of the keyboard are not getting inputted properly. Anysoftkeyboard doesn't handle shift key on the keyboard properly for Indian Language(s). 
For instance, 
Consider this Key element

```
<Key android:codes="0x094C" android:keyWidth="7%p" custom:shiftedCodes="0x0914" custom:shiftedKeyLabel="\u0914" android:horizontalGap="1.5%p" android:popupCharacters="\u0914" android:keyEdgeFlags="left"/>
```

When Shift Key is pressed, the label on the above key changes from Unshift to shift(i.e from U+094C to U+0914) . But, when the above key is pressed the text entered in the editor is of the Unshift state(i.e U+094C).

Kindly let us know how to use Shift key for the above issue.

**Comment by friesenkiwi** [comment]
@menny I know, this is old, but can you maybe answer this question? It might help future contributors...

**Comment by ikocevski** [comment]
@menny I'd like to know about this too, it happens even in the default English keyboard. For example when the additional number row appears when entering a password if you press `Shift` the numbers are replaced with symbols but when you click on any symbol it actually inserts the number that was there before.

Isn't this a bug?

**Comment by menny** [comment]
This should work... sounds like a bug. I'll try to reproduce this, but it will take some time since I'm on vacation rn
