### ISSUE TITLE
Request for Portuguese keyboard

### ISSUE THREAD

**Issue by rosariotech** [AnySoftKeyboard/LanguagePack#92]
If possible, please make an alternative keyboard layout without the hyphen key. I always make typo errors because of it.

**Comment by friesenkiwi** [comment]
Actually, I would rather go with removing the - (hyphen) key altogether, because it is inconsistent to other layouts and the hyphen is available via the bottom row.

**Comment by friesenkiwi** [comment]
This has been implemented now and a release is triggered for F-Droid, Play store will follow

**Comment by menny** [comment]
Pushed to Play-Store. Will be available shortly.
