### ISSUE TITLE
Czech layout: dictionary doesn't work

### ISSUE THREAD

**Issue by knezi** [AnySoftKeyboard/LanguagePack#93]
Hallo,
I use German, English and Czech layouts. For German and English everything works, but for Czech there's no autocorrection.
Anysoftkeyboard: 1.8.1333
Czech layout: 2.0.0

**Comment by friesenkiwi** [comment]
Thanks for the report, you are totally right, this is a big bug I'm responsible for, stemming from here: https://github.com/AnySoftKeyboard/LanguagePack/blob/Czech/src/main/res/xml/dictionaries.xml
I just forgot to change the file when resurrecting. :-(
I hope I can release a new version this week.

**Comment by friesenkiwi** [comment]
This has been implemented now and a release is triggered for F-Droid, Play store will follow.

**Comment by menny** [comment]
Pushed to Play-Store. Will be available shortly.
