### ISSUE TITLE
Spanish Dvorak layout: dictionary doesn't work

### ISSUE THREAD

**Issue by paxet** [AnySoftKeyboard/LanguagePack#94]
Hi!
I'm trying the Spanish Dvorak layout, but it defaults to the English Dictionary. Looking through settings, I've seen it like Dvorak - (en). 

Using latest version from F-Droid but with the Play Store one is the same.

**Comment by friesenkiwi** [comment]
Thank you for your report, you are right this is a bug (https://github.com/AnySoftKeyboard/LanguagePack/blob/Spanish/src/main/res/xml/keyboards.xml).
I'm hoping to be able to fix and re-release this week.

**Comment by friesenkiwi** [comment]
This has been implemented now and a release is triggered for F-Droid, Play store will follow.

**Comment by menny** [comment]
Pushed to Play-Store. Will be available shortly.
