### ISSUE TITLE
Spanish Dvorak layout: Wrong default accents

### ISSUE THREAD

**Issue by Felfa** [AnySoftKeyboard/LanguagePack#96]
The ASK Spanish Dvorak layout defaults to grave accents (`) when holding down "a", "e" and "o" keys, and they're never used in spanish language. It defaults to diaeresis (¨) too when holding down "u" (used in some cases). And it defaults to "ī" (i with macron) when "i" key is held down, symbol that isn't used in spanish language at all.

The acute mark (´) is the most used accent in spanish language and it would be nice if it's the default choice when holding down every vowel key. It's annoying when you're typing fast because it slows you down to having always to choose the right accent manually every time you need to put an accented vowel.

**Comment by friesenkiwi** [comment]
This has been implemented now and a release is triggered for F-Droid, Play store will follow.

**Comment by menny** [comment]
Pushed to Play-Store. Will be available shortly.

**Comment by Lonami** [comment]
While I agree that a lot of accents weren't used, the ü (which has been removed), was actually used for words like *Pingüino* or *Cigüeña*. Also, I see no reason to remove the others even after making our accent (áéíóú and ü) the defaults. They can still be useful when quickly writing something on a different language, and I don't think people is bothered to have them there as another option.
